// ============================================
// API Request Practice Page
// Location: /src/pages/lab/APIRequestPractice.jsx
// ============================================

import { useState } from 'react';
import { 
  Code, CheckCircle, XCircle, AlertTriangle, 
  Info, RotateCcw, Lightbulb, Shield, Sparkles, 
  BookOpen, Zap, Globe
} from 'lucide-react';
import Card from '../../components/ui/Card';
import Button from '../../components/ui/Button';
import Input from '../../components/ui/Input';

const APIRequestPractice = () => {
  // Configuration state
  const [config, setConfig] = useState({
    requestType: 'add rule',
    action: 'allow',
    portOrService: 'port',
    port: '',
    service: '',
    protocol: 'tcp',
    direction: '',
    ipv4: true,
    ipv6: false,
    source: ''
  });

  // API Request state
  const [apiRequest, setApiRequest] = useState({
    method: '',
    endpoint: '',
    headers: '',
    body: ''
  });

  // Practice state
  const [result, setResult] = useState(null);
  const [attemptsLeft, setAttemptsLeft] = useState(5);
  const [maxAttempts] = useState(5);
  const [showExamples, setShowExamples] = useState(false);
  const [difficulty, setDifficulty] = useState('easy');
  const [hintsUsed, setHintsUsed] = useState(0);
  const [showHint, setShowHint] = useState(false);

  // Mock token (in real system, this would be generated by backend)
  const mockToken = 'jAoCGYXugDkHjSNYAa6C8xQ38D2kD10RsHDz1N4XigaVSHL2';

  // Validate IP address or subnet (IPv4 and IPv6)
  const validateIPAddress = (ip) => {
    if (!ip) return true; 
    
    // IPv4 with CIDR
    const ipv4CidrRegex = /^(\d{1,3}\.){3}\d{1,3}\/\d{1,2}$/;
    if (ipv4CidrRegex.test(ip)) {
      const [address, mask] = ip.split('/');
      const octets = address.split('.').map(Number);
      const maskNum = parseInt(mask);
      return octets.every(octet => octet >= 0 && octet <= 255) && maskNum >= 0 && maskNum <= 32;
    }
    
    // IPv4 regular
    const ipv4Regex = /^(\d{1,3}\.){3}\d{1,3}$/;
    if (ipv4Regex.test(ip)) {
      const octets = ip.split('.').map(Number);
      return octets.every(octet => octet >= 0 && octet <= 255);
    }

    // IPv6 with CIDR
    const ipv6CidrRegex = /^([0-9a-fA-F]{0,4}:){2,7}[0-9a-fA-F]{0,4}\/\d{1,3}$/;
    if (ipv6CidrRegex.test(ip)) {
      const maskNum = parseInt(ip.split('/')[1]);
      return maskNum >= 0 && maskNum <= 128;
    }
    
    // IPv6 regular
    const ipv6Regex = /^([0-9a-fA-F]{0,4}:){2,7}[0-9a-fA-F]{0,4}$/;
    if (ipv6Regex.test(ip)) return true;

    // IPv6 shortened
    const ipv6ShortRegex = /^::([0-9a-fA-F]{0,4}:){0,6}[0-9a-fA-F]{0,4}$|^([0-9a-fA-F]{0,4}:){1,7}:$/;
    if (ipv6ShortRegex.test(ip)) return true;
    
    return false;
  };

  // Detect IP version from source address
  const detectIPVersion = (ip) => {
    if (!ip) return { ipv4: false, ipv6: false };
    
    // Check IPv4
    const ipv4Regex = /^(\d{1,3}\.){3}\d{1,3}(\/\d{1,2})?$/;
    if (ipv4Regex.test(ip)) {
      const address = ip.split('/')[0];
      const octets = address.split('.').map(Number);
      if (octets.every(octet => octet >= 0 && octet <= 255)) {
        return { ipv4: true, ipv6: false };
      }
    }
    
    // Check IPv6 (any format with colons)
    if (ip.includes(':')) {
      return { ipv4: false, ipv6: true };
    }
    
    return { ipv4: false, ipv6: false };
  };

  // Handle source change with auto IP version detection
  const handleSourceChange = (value) => {
    const detected = detectIPVersion(value);
    setConfig({ 
      ...config, 
      source: value,
      ipv4: detected.ipv4,
      ipv6: detected.ipv6
    });
  };

  // Generate expected API request based on configuration
  const generateExpectedRequest = () => {
    const serverIP = 'localhost:5000';
    let expectedEndpoint = '';
    let expectedMethod = '';
    let expectedHeaders = {};
    let expectedBody = null;

    if (config.requestType === 'view rule') {
      expectedMethod = 'GET';
      expectedEndpoint = `http://${serverIP}/api/firewall/status`;
      expectedHeaders = {
        'Authorization': `Bearer ${mockToken}`
      };
    } else if (config.requestType === 'add rule') {
      expectedMethod = 'POST';
      expectedEndpoint = `http://${serverIP}/api/firewall`;
      expectedHeaders = {
        'Content-Type': 'application/json',
        'Authorization': `Bearer ${mockToken}`
      };
      expectedBody = {
        action: config.action,
        protocol: config.protocol
      };

      // Add port or service
      if (config.portOrService === 'port' && config.port) {
        expectedBody.port = config.port;
      } else if (config.portOrService === 'service' && config.service) {
        expectedBody.service = config.service;
      }

      // Add optional fields
      if (config.direction) expectedBody.direction = config.direction;
      if (config.source) expectedBody.source = config.source;
      
      // Always include ipv4 and ipv6 as boolean
      expectedBody.ipv4 = config.ipv4;
      expectedBody.ipv6 = config.ipv6;

    } else if (config.requestType === 'delete rule') {
      expectedMethod = 'DELETE';
      expectedEndpoint = `http://${serverIP}/api/firewall`;
      expectedHeaders = {
        'Content-Type': 'application/json',
        'Authorization': `Bearer ${mockToken}`
      };
      expectedBody = {
        action: config.action,
        protocol: config.protocol
      };

      // Add port or service
      if (config.portOrService === 'port' && config.port) {
        expectedBody.port = config.port;
      } else if (config.portOrService === 'service' && config.service) {
        expectedBody.service = config.service;
      }

      // Add optional fields
      if (config.direction) expectedBody.direction = config.direction;
      if (config.source) expectedBody.source = config.source;
      
      // Always include ipv4 and ipv6 as boolean
      expectedBody.ipv4 = config.ipv4;
      expectedBody.ipv6 = config.ipv6;
    }

    return { expectedMethod, expectedEndpoint, expectedHeaders, expectedBody };
  };

  // Validate user's API request
  const handleCheckRequest = () => {
    const { expectedMethod, expectedEndpoint, expectedHeaders, expectedBody } = generateExpectedRequest();
    const newAttemptsLeft = attemptsLeft - 1;
    setAttemptsLeft(newAttemptsLeft);

    let isCorrect = true;
    let errors = [];

    // Check method
    if (apiRequest.method.trim().toUpperCase() !== expectedMethod.toUpperCase()) {
      isCorrect = false;
      errors.push(`HTTP method is incorrect (expected: ${expectedMethod})`);
    }

    // Check endpoint
    if (apiRequest.endpoint.trim().toLowerCase() !== expectedEndpoint.toLowerCase()) {
      isCorrect = false;
      errors.push('Endpoint is incorrect');
    }

    // Check headers
    try {
      const userHeaders = JSON.parse(apiRequest.headers);
      for (const [key, value] of Object.entries(expectedHeaders)) {
        if (!userHeaders[key] || userHeaders[key] !== value) {
          isCorrect = false;
          errors.push(`Header "${key}" is missing or incorrect`);
          break;
        }
      }
    } catch (e) {
      isCorrect = false;
      errors.push('Headers must be valid JSON format');
    }

    // Check body (if required)
    if (expectedBody) {
      try {
        const userBody = JSON.parse(apiRequest.body);
        for (const [key, value] of Object.entries(expectedBody)) {
          // Use hasOwnProperty to check if key exists (to handle false values correctly)
          if (!userBody.hasOwnProperty(key) || userBody[key] !== value) {
            isCorrect = false;
            errors.push(`Body field "${key}" is missing or incorrect`);
            break;
          }
        }
      } catch (e) {
        isCorrect = false;
        errors.push('Request body must be valid JSON format');
      }
    }

    const showAnswer = newAttemptsLeft === 0;

    if (isCorrect) {
      setResult({
        correct: true,
        message: 'Perfect! Your API request is correct! 🎉',
        expectedMethod,
        expectedEndpoint,
        expectedHeaders,
        expectedBody,
        showAnswer: true
      });
    } else {
      setResult({
        correct: false,
        message: showAnswer 
          ? 'Out of attempts! Here\'s the correct answer:' 
          : `Incorrect. You have ${newAttemptsLeft} attempt${newAttemptsLeft !== 1 ? 's' : ''} remaining.`,
        errors,
        expectedMethod,
        expectedEndpoint,
        expectedHeaders,
        expectedBody,
        showAnswer
      });
    }
  };

  // Reset all fields
  const handleReset = () => {
    setConfig({
      requestType: 'add rule',
      action: 'allow',
      portOrService: 'port',
      port: '',
      service: '',
      protocol: 'tcp',
      direction: '',
      ipv4: true,
      ipv6: false,
      source: ''
    });
    setApiRequest({
      method: '',
      endpoint: '',
      headers: '',
      body: ''
    });
    setResult(null);
    setShowHint(false);
    setAttemptsLeft(maxAttempts);
    setHintsUsed(0);
  };

  // Try another request (after success or failure)
  const handleTryAnother = () => {
    setConfig({
      requestType: 'add rule',
      action: 'allow',
      portOrService: 'port',
      port: '',
      service: '',
      protocol: 'tcp',
      direction: '',
      ipv4: false,
      ipv6: false,
      source: ''
    });
    setApiRequest({
      method: '',
      endpoint: '',
      headers: '',
      body: ''
    });
    setResult(null);
    setShowHint(false);
    setAttemptsLeft(maxAttempts);
    setHintsUsed(0);
  };

  // Quick fill with random values based on difficulty
  const handleQuickFill = () => {
    const actions = ['allow', 'deny', 'reject'];
    const protocols = ['tcp', 'udp'];
    const directions = ['', 'in', 'out'];
    const requestTypes = difficulty === 'easy' ? ['view rule', 'add rule'] : ['view rule', 'add rule', 'delete rule'];
    const ports = {
      easy: ['22', '80', '443'],
      medium: ['8080', '3000', '4000'],
      hard: ['2222', '8443', '9090']
    };
    const services = ['ssh', 'http', 'https', 'mysql', 'postgresql'];

    const requestType = requestTypes[Math.floor(Math.random() * requestTypes.length)];
    
    let newConfig = {
      requestType,
      action: actions[Math.floor(Math.random() * actions.length)],
      portOrService: Math.random() > 0.5 ? 'port' : 'service',
      port: '',
      service: '',
      protocol: protocols[Math.floor(Math.random() * protocols.length)],
      direction: difficulty === 'easy' ? '' : directions[Math.floor(Math.random() * directions.length)],
      ipv4: true,
      ipv6: true,
      source: ''
    };

    if (requestType !== 'view rule') {
      if (newConfig.portOrService === 'port') {
        newConfig.port = ports[difficulty][Math.floor(Math.random() * ports[difficulty].length)];
      } else {
        newConfig.service = services[Math.floor(Math.random() * services.length)];
      }

      if (difficulty === 'medium' && Math.random() > 0.5) {
        newConfig.source = '192.168.1.100';
        newConfig.ipv4 = true;
      } else if (difficulty === 'hard') {
        newConfig.source = Math.random() > 0.5 ? '192.168.1.0/24' : '2001:db8::1';
        newConfig.ipv4 = newConfig.source.includes('.') ? true : false;
        newConfig.ipv6 = newConfig.source.includes(':') ? true : false;
      }
    }

    setConfig(newConfig);
    setApiRequest({
      method: '',
      endpoint: '',
      headers: '',
      body: ''
    });
    setResult(null);
    setShowHint(false);
  };

  // Show progressive hints
  const handleShowHint = () => {
    setShowHint(true);
    setHintsUsed(hintsUsed + 1);
  };

  // Generate hint based on configuration
  const generateHint = () => {
    if (hintsUsed === 0) {
      return "Start by checking the endpoint URL. Remember the server is at localhost:5000";
    } else if (hintsUsed === 1) {
      return `For ${config.requestType} requests, check which HTTP method to use and what the route is`;
    } else if (hintsUsed === 2) {
      return "Headers should be in JSON format. All requests need Authorization header";
    } else {
      return `The endpoint should be: ${generateExpectedRequest().expectedEndpoint}`;
    }
  };

  // Check if form is complete enough to submit
  const isFormValid = () => {
    if (config.requestType === 'view rule') return true;
    
    if (config.portOrService === 'port' && !config.port) return false;
    if (config.portOrService === 'service' && !config.service) return false;
    if (config.source && !validateIPAddress(config.source)) return false;
    if (!config.ipv4 && !config.ipv6) return false;
    
    return true;
  };

  return (
    <div className="space-y-6">
      {/* Header */}
      <div className="mb-6">
        <div className="flex items-center gap-3 mb-2">
          <div className="bg-gradient-to-br from-cyan-500 to-blue-600 p-3 rounded-lg">
            <Code className="w-8 h-8 text-white" />
          </div>
          <div>
            <h1 className="text-3xl font-bold text-white">API Request Practice</h1>
            <p className="text-slate-400 mt-1">
              Practice building API requests for firewall configuration
            </p>
          </div>
        </div>
      </div>

      {/* Introduction */}
      <Card className="bg-gradient-to-r from-blue-500/10 to-cyan-500/10 border-blue-500/30">
        <div className="flex items-start gap-4">
          <Info className="w-6 h-6 text-blue-400 flex-shrink-0 mt-1" />
          <div>
            <h3 className="text-lg font-bold text-white mb-2">How This Works</h3>
            <ol className="space-y-2 text-slate-300">
              <li className="flex items-start gap-2">
                <span className="text-blue-400 font-semibold">1.</span>
                <span>Configure your desired API request using the options below</span>
              </li>
              <li className="flex items-start gap-2">
                <span className="text-blue-400 font-semibold">2.</span>
                <span>Fill in the API endpoint, headers and request body</span>
              </li>
              <li className="flex items-start gap-2">
                <span className="text-blue-400 font-semibold">3.</span>
                <span>Click "Check Request" to verify if your API request is correct</span>
              </li>
            </ol>
          </div>
        </div>
      </Card>

      {/* Difficulty & Quick Actions */}
      <div className="grid grid-cols-1 md:grid-cols-2 gap-4">
        {/* Difficulty Selector */}
        <Card>
          <h3 className="text-lg font-semibold text-white mb-3 flex items-center gap-2">
            <Zap className="w-5 h-5 text-yellow-500" />
            Difficulty Level (Quick Fill)
          </h3>
          <div className="grid grid-cols-3 gap-2">
            {[
              { value: 'easy', label: 'Easy', color: 'green' },
              { value: 'medium', label: 'Medium', color: 'yellow' },
              { value: 'hard', label: 'Hard', color: 'red' }
            ].map((level) => (
              <button
                key={level.value}
                onClick={() => setDifficulty(level.value)}
                className={`px-3 py-2 rounded-lg border-2 transition-all text-sm font-semibold ${
                  difficulty === level.value
                    ? `bg-${level.color}-500/20 border-${level.color}-500 text-${level.color}-400`
                    : 'bg-slate-700/30 border-slate-600 text-slate-300 hover:border-slate-500'
                }`}
              >
                {level.label}
              </button>
            ))}
          </div>
          <p className="text-slate-400 text-xs mt-2">
            {difficulty === 'easy' && 'Basic requests: view and simple add'}
            {difficulty === 'medium' && 'Includes optional fields and source'}
            {difficulty === 'hard' && 'Complex requests with IPv6 and delete'}
          </p>
        </Card>

        {/* Quick Actions */}
        <Card>
          <h3 className="text-lg font-semibold text-white mb-3 flex items-center gap-2">
            <Sparkles className="w-5 h-5 text-purple-500" />
            Quick Actions
          </h3>
          <div className="flex gap-2">
            <Button
              variant="outline"
              onClick={handleQuickFill}
              className="flex items-center gap-2 flex-1"
            >
              <Sparkles className="w-4 h-4" />
              Quick Fill
            </Button>
            <Button
              variant="outline"
              onClick={() => setShowExamples(!showExamples)}
              className="flex items-center gap-2 flex-1"
            >
              <BookOpen className="w-4 h-4" />
              Examples
            </Button>
          </div>
        </Card>
      </div>

      {/* Examples Section */}
      {showExamples && (
        <Card className="bg-gradient-to-r from-purple-500/10 to-pink-500/10 border-purple-500/30">
          <div className="flex items-center justify-between mb-4">
            <h3 className="text-xl font-bold text-white flex items-center gap-2">
              <BookOpen className="w-6 h-6 text-purple-500" />
              Example API Requests
            </h3>
            <button
              onClick={() => setShowExamples(false)}
              className="text-slate-400 hover:text-white"
            >
              <XCircle className="w-5 h-5" />
            </button>
          </div>
          <div className="space-y-4">
            <div>
              <p className="text-sm font-semibold text-purple-400 mb-2">View Firewall Status (GET):</p>
              <div className="bg-slate-900 rounded-lg p-3 border border-slate-700 space-y-2 text-sm">
                <div><span className="text-cyan-400">Endpoint:</span> <span className="text-green-400 font-mono">http://localhost:5000/api/firewall/status</span></div>
                <div><span className="text-cyan-400">Headers:</span> <code className="text-purple-400 font-mono">{`{"Authorization": "Bearer <token>"}`}</code></div>
              </div>
            </div>
            <div>
              <p className="text-sm font-semibold text-purple-400 mb-2">Add Firewall Rule (POST):</p>
              <div className="bg-slate-900 rounded-lg p-3 border border-slate-700 space-y-2 text-sm">
                <div><span className="text-cyan-400">Endpoint:</span> <span className="text-green-400 font-mono">http://localhost:5000/api/firewall</span></div>
                <div><span className="text-cyan-400">Headers:</span> <code className="text-purple-400 font-mono">{`{"Content-Type": "application/json", "Authorization": "Bearer <token>"}`}</code></div>
                <div><span className="text-cyan-400">Body:</span> <code className="text-orange-400 font-mono">{`{"action": "allow", "port": "22", "protocol": "tcp", "ipv4": false, "ipv6": false}`}</code></div>
              </div>
            </div>
            <div>
              <p className="text-sm font-semibold text-purple-400 mb-2">Delete Firewall Rule (DELETE):</p>
              <div className="bg-slate-900 rounded-lg p-3 border border-slate-700 space-y-2 text-sm">
                <div><span className="text-cyan-400">Endpoint:</span> <span className="text-green-400 font-mono">http://localhost:5000/api/firewall</span></div>
                <div><span className="text-cyan-400">Headers:</span> <code className="text-purple-400 font-mono">{`{"Content-Type": "application/json", "Authorization": "Bearer <token>"}`}</code></div>
                <div><span className="text-cyan-400">Body:</span> <code className="text-orange-400 font-mono">{`{"action": "allow", "service": "ssh", "protocol": "tcp", "ipv4": true, "ipv6": false}`}</code></div>
              </div>
            </div>
          </div>
        </Card>
      )}

      {/* Configuration Section - 2 Column Layout */}
      <Card>
        <h2 className="text-2xl font-bold text-white mb-6 flex items-center gap-2">
          <Shield className="w-6 h-6 text-cyan-500" />
          Configure API Request
        </h2>

        <div className="grid grid-cols-1 lg:grid-cols-2 gap-x-8 gap-y-5">
          {/* LEFT COLUMN */}
          {/* Request Type */}
          <div>
            <label className="block text-sm font-semibold text-white mb-2">
              Request Type <span className="text-red-400">*</span>
            </label>
            <div className="grid grid-cols-3 gap-2">
              {[
                { value: 'view rule', label: 'View Rule' },
                { value: 'add rule', label: 'Add Rule' },
                { value: 'delete rule', label: 'Delete Rule' }
              ].map((type) => (
                <button
                  key={type.value}
                  onClick={() => setConfig({ ...config, requestType: type.value })}
                  className={`px-3 py-2 rounded-lg border-2 transition-all text-sm ${
                    config.requestType === type.value
                      ? 'bg-cyan-500/20 border-cyan-500 text-cyan-400 font-semibold'
                      : 'bg-slate-700/30 border-slate-600 text-slate-300 hover:border-slate-500'
                  }`}
                >
                  {type.label}
                </button>
              ))}
            </div>
          </div>

          {/* RIGHT COLUMN */}
          {/* Protocol (only for add/delete) */}
          {config.requestType !== 'view rule' && (
            <div>
              <label className="block text-sm font-semibold text-white mb-2">
                Protocol <span className="text-red-400">*</span>
              </label>
              <div className="grid grid-cols-2 gap-2">
                {['tcp', 'udp'].map((protocol) => (
                  <button
                    key={protocol}
                    onClick={() => setConfig({ ...config, protocol })}
                    className={`px-3 py-2 rounded-lg border-2 transition-all text-sm ${
                      config.protocol === protocol
                        ? 'bg-purple-500/20 border-purple-500 text-purple-400 font-semibold'
                        : 'bg-slate-700/30 border-slate-600 text-slate-300 hover:border-slate-500'
                    }`}
                  >
                    {protocol.toUpperCase()}
                  </button>
                ))}
              </div>
            </div>
          )}

          {/* Action (only for add/delete) */}
          {config.requestType !== 'view rule' && (
            <div>
              <label className="block text-sm font-semibold text-white mb-2">
                Action <span className="text-red-400">*</span>
              </label>
              <div className="grid grid-cols-3 gap-2">
                {['allow', 'deny', 'reject'].map((action) => (
                  <button
                    key={action}
                    onClick={() => setConfig({ ...config, action })}
                    className={`px-3 py-2 rounded-lg border-2 transition-all text-sm ${
                      config.action === action
                        ? 'bg-orange-500/20 border-orange-500 text-orange-400 font-semibold'
                        : 'bg-slate-700/30 border-slate-600 text-slate-300 hover:border-slate-500'
                    }`}
                  >
                    {action.toUpperCase()}
                  </button>
                ))}
              </div>
            </div>
          )}

          {/* Port or Service selector (only for add/delete) */}
          {config.requestType !== 'view rule' && (
            <div>
              <label className="block text-sm font-semibold text-white mb-2">
                Specify By <span className="text-red-400">*</span>
              </label>
              <div className="grid grid-cols-2 gap-2">
                <button
                  onClick={() => setConfig({ ...config, portOrService: 'port', service: '' })}
                  className={`px-3 py-2 rounded-lg border-2 transition-all text-sm ${
                    config.portOrService === 'port'
                      ? 'bg-blue-500/20 border-blue-500 text-blue-400 font-semibold'
                      : 'bg-slate-700/30 border-slate-600 text-slate-300 hover:border-slate-500'
                  }`}
                >
                  Port Number
                </button>
                <button
                  onClick={() => setConfig({ ...config, portOrService: 'service', port: '' })}
                  className={`px-3 py-2 rounded-lg border-2 transition-all text-sm ${
                    config.portOrService === 'service'
                      ? 'bg-blue-500/20 border-blue-500 text-blue-400 font-semibold'
                      : 'bg-slate-700/30 border-slate-600 text-slate-300 hover:border-slate-500'
                  }`}
                >
                  Service Name
                </button>
              </div>
            </div>
          )}

          {/* Port input (only if port is selected) */}
          {config.requestType !== 'view rule' && config.portOrService === 'port' && (
            <div>
              <label className="block text-sm font-semibold text-white mb-2">
                Port Number <span className="text-red-400">*</span>
              </label>
              <Input
                type="text"
                placeholder="22"
                value={config.port}
                onChange={(e) => setConfig({ ...config, port: e.target.value })}
              />
            </div>
          )}

          {/* Service input (only if service is selected) */}
          {config.requestType !== 'view rule' && config.portOrService === 'service' && (
            <div>
              <label className="block text-sm font-semibold text-white mb-2">
                Service Name <span className="text-red-400">*</span>
              </label>
              <Input
                type="text"
                placeholder="ssh"
                value={config.service}
                onChange={(e) => setConfig({ ...config, service: e.target.value })}
              />
              <p className="text-slate-400 text-xs mt-1">e.g., ssh, http, https, mysql</p>
            </div>
          )}

          {/* Direction (only for add/delete) */}
          {(config.requestType === 'add rule' || config.requestType === 'delete rule') && (
            <div>
              <label className="block text-sm font-semibold text-white mb-2">
                Direction <span className="text-slate-400 text-xs">(Optional)</span>
              </label>
              <div className="grid grid-cols-3 gap-2">
                <button
                  onClick={() => setConfig({ ...config, direction: '' })}
                  className={`px-3 py-2 rounded-lg border-2 transition-all text-sm ${
                    config.direction === ''
                      ? 'bg-slate-500/20 border-slate-400 text-slate-300 font-semibold'
                      : 'bg-slate-700/30 border-slate-600 text-slate-400 hover:border-slate-500'
                  }`}
                >
                  None
                </button>
                {['in', 'out'].map((dir) => (
                  <button
                    key={dir}
                    onClick={() => setConfig({ ...config, direction: dir })}
                    className={`px-3 py-2 rounded-lg border-2 transition-all text-sm ${
                      config.direction === dir
                        ? 'bg-blue-500/20 border-blue-500 text-blue-400 font-semibold'
                        : 'bg-slate-700/30 border-slate-600 text-slate-300 hover:border-slate-500'
                    }`}
                  >
                    {dir.toUpperCase()}
                  </button>
                ))}
              </div>
            </div>
          )}

          {/* Source (only for add/delete) */}
          {(config.requestType === 'add rule' || config.requestType === 'delete rule') && (
            <div className="lg:col-span-1">
              <label className="block text-sm font-semibold text-white mb-2">
                Source <span className="text-slate-400 text-xs">(Optional)</span>
              </label>
              <Input
                type="text"
                placeholder="192.168.1.100 or 2001:db8::1"
                value={config.source}
                onChange={(e) => handleSourceChange(e.target.value)}
                className={config.source && !validateIPAddress(config.source) ? 'border-red-500' : ''}
              />
              {config.source && !validateIPAddress(config.source) && (
                <p className="text-red-400 text-xs mt-1 flex items-center gap-1">
                  <XCircle className="w-3 h-3" />
                  Invalid IPv4/IPv6 address or subnet
                </p>
              )}
              {config.source && validateIPAddress(config.source) && (
                <p className="text-green-400 text-xs mt-1 flex items-center gap-1">
                  <CheckCircle className="w-3 h-3" />
                  IP version auto-detected: {config.ipv4 ? 'IPv4' : 'IPv6'}
                </p>
              )}
            </div>
          )}

          {/* IPv4/IPv6 checkboxes (only for add/delete) */}
          {config.requestType !== 'view' && (
            <div className="lg:col-span-2">
              <label className="block text-sm font-semibold text-white mb-2">
                IP Version <span className="text-red-400">* (Select at least one)</span>
              </label>
              <div className="flex gap-4">
                <label className={`flex items-center gap-2 ${config.source ? 'cursor-not-allowed opacity-50' : 'cursor-pointer'}`}>
                  <input
                    type="checkbox"
                    checked={config.ipv4}
                    onChange={(e) => setConfig({ ...config, ipv4: e.target.checked })}
                    disabled={config.source !== ''}
                    className="w-4 h-4 rounded border-slate-600 bg-slate-700 text-cyan-500 focus:ring-cyan-500 disabled:opacity-50 disabled:cursor-not-allowed"
                  />
                  <span className="text-slate-300 text-sm">IPv4</span>
                </label>
                <label className={`flex items-center gap-2 ${config.source ? 'cursor-not-allowed opacity-50' : 'cursor-pointer'}`}>
                  <input
                    type="checkbox"
                    checked={config.ipv6}
                    onChange={(e) => setConfig({ ...config, ipv6: e.target.checked })}
                    disabled={config.source !== ''}
                    className="w-4 h-4 rounded border-slate-600 bg-slate-700 text-cyan-500 focus:ring-cyan-500 disabled:opacity-50 disabled:cursor-not-allowed"
                  />
                  <span className="text-slate-300 text-sm">IPv6</span>
                </label>
              </div>
              {config.source && (
                <p className="text-slate-400 text-xs mt-1">
                  💡 IP version is automatically detected from the source address
                </p>
              )}
              {!config.ipv4 && !config.ipv6 && !config.source && (
                <p className="text-red-400 text-xs mt-1 flex items-center gap-1">
                  <XCircle className="w-3 h-3" />
                  Please select at least one IP version
                </p>
              )}
            </div>
          )}

          {/* Action Buttons - Full width at bottom */}
          <div className="lg:col-span-2 pt-4 border-t border-slate-700 flex gap-2">
            <Button
              variant="outline"
              onClick={handleReset}
              className="flex items-center gap-2"
              size="sm"
            >
              <RotateCcw className="w-4 h-4" />
              Reset
            </Button>
          </div>
        </div>
      </Card>

      {/* Current Configuration Summary */}
      <Card className="bg-slate-800/50 border-slate-600">
        <h3 className="text-lg font-semibold text-white mb-3">Current Configuration</h3>
        <div className="grid grid-cols-2 md:grid-cols-3 lg:grid-cols-4 gap-4 text-sm">
          <div>
            <span className="text-slate-400 block mb-1">Request Type:</span>
            <span className="text-cyan-400 font-mono font-semibold">{config.requestType || '-'}</span>
          </div>
          {config.requestType !== 'view rule' && (
            <>
              <div>
                <span className="text-slate-400 block mb-1">Action:</span>
                <span className="text-orange-400 font-mono font-semibold">{config.action || '-'}</span>
              </div>
              <div>
                <span className="text-slate-400 block mb-1">Port/Service:</span>
                <span className="text-purple-400 font-mono font-semibold">
                  {config.portOrService === 'port' ? config.port || '-' : config.service || '-'}
                </span>
              </div>
              <div>
                <span className="text-slate-400 block mb-1">Protocol:</span>
                <span className="text-purple-400 font-mono font-semibold">{config.protocol || '-'}</span>
              </div>
              <div>
                <span className="text-slate-400 block mb-1">Direction:</span>
                <span className="text-blue-400 font-mono font-semibold">{config.direction || 'none'}</span>
              </div>
              <div>
                <span className="text-slate-400 block mb-1">Source:</span>
                <span className="text-cyan-400 font-mono text-xs">{config.source || 'any'}</span>
              </div>
              <div>
                <span className="text-slate-400 block mb-1">IP Version:</span>
                <span className="text-green-400 font-mono font-semibold">
                  {config.ipv4 && config.ipv6 ? 'IPv4 + IPv6' : 
                   config.ipv4 ? 'IPv4' : 
                   config.ipv6 ? 'IPv6' : 
                   'none'}
                </span>
              </div>
            </>
          )}
        </div>
      </Card>

      {/* API Request Section */}
      <Card>
        <h2 className="text-2xl font-bold text-white mb-4 flex items-center gap-2">
          <Globe className="w-6 h-6 text-blue-500" />
          Build API Request
        </h2>

        {/* Attempts Counter */}
        <div className="mb-4 flex items-center justify-between p-3 bg-slate-800/50 rounded-lg border border-slate-700">
          <span className="text-slate-400 text-sm">Attempts Remaining:</span>
          <span className={`text-lg font-bold ${
            attemptsLeft > 3 ? 'text-green-400' : 
            attemptsLeft > 1 ? 'text-yellow-400' : 
            'text-red-400'
          }`}>
            {attemptsLeft} / {maxAttempts}
          </span>
        </div>

        <div className="space-y-4">
          {/* Mock Token Display */}
          <div className="bg-cyan-500/10 border border-cyan-500/30 rounded-lg p-4">
            <div className="flex items-start gap-3">
              <Info className="w-5 h-5 text-cyan-400 flex-shrink-0 mt-0.5" />
              <div className="flex-1">
                <h3 className="text-sm font-semibold text-cyan-400 mb-2">Access Token (Use this in your request)</h3>
                <div className="bg-slate-900 rounded p-2 overflow-x-auto">
                  <code className="text-green-400 text-xs font-mono break-all">{mockToken}</code>
                </div>
              </div>
            </div>
          </div>

          {/* HTTP Method Input */}
          <div>
            <label className="block text-sm font-semibold text-white mb-2">
              HTTP Method:
            </label>
            <Input
              type="text"
              placeholder="GET, POST, or DELETE"
              value={apiRequest.method}
              onChange={(e) => setApiRequest({ ...apiRequest, method: e.target.value })}
              disabled={!isFormValid() || attemptsLeft === 0}
            />
            <p className="text-slate-400 text-xs mt-1 flex items-center gap-1">
              <Info className="w-3 h-3" />
              Enter the HTTP method (GET, POST, or DELETE)
            </p>
          </div>

          {/* API Endpoint Input */}
          <div>
            <label className="block text-sm font-semibold text-white mb-2">
              API Endpoint:
            </label>
            <Input
              type="text"
              placeholder="http://localhost:5000/api/..."
              value={apiRequest.endpoint}
              onChange={(e) => setApiRequest({ ...apiRequest, endpoint: e.target.value })}
              disabled={!isFormValid() || attemptsLeft === 0}
            />
            <p className="text-slate-400 text-xs mt-1 flex items-center gap-1">
              <Info className="w-3 h-3" />
              Include full URL with http://localhost:5000
            </p>
          </div>

          {/* Request Headers Input */}
          <div>
            <label className="block text-sm font-semibold text-white mb-2">
              Request Headers (JSON format):
            </label>
            <textarea
              value={apiRequest.headers}
              onChange={(e) => setApiRequest({ ...apiRequest, headers: e.target.value })}
              placeholder='{"Authorization": "Bearer <token>", "Content-Type": "application/json"}'
              className="w-full bg-slate-900 text-cyan-400 font-mono px-4 py-3 rounded-lg border-2 border-slate-700 focus:border-blue-500 transition-colors outline-none placeholder:text-slate-600 min-h-[100px]"
              disabled={!isFormValid() || attemptsLeft === 0}
            />
          </div>

          {/* Request Body Input (only for POST/DELETE) */}
          {config.requestType !== 'view rule' && (
            <div>
              <label className="block text-sm font-semibold text-white mb-2">
                Request Body (JSON format):
              </label>
              <textarea
                value={apiRequest.body}
                onChange={(e) => setApiRequest({ ...apiRequest, body: e.target.value })}
                placeholder='{"action": "allow", "port": "22", "protocol": "tcp"}'
                className="w-full bg-slate-900 text-purple-400 font-mono px-4 py-3 rounded-lg border-2 border-slate-700 focus:border-purple-500 transition-colors outline-none placeholder:text-slate-600 min-h-[120px]"
                disabled={!isFormValid() || attemptsLeft === 0}
              />
            </div>
          )}

          {/* Check & Hint Buttons */}
          <div className="flex gap-3">
            <Button
              onClick={handleCheckRequest}
              disabled={!isFormValid() || !apiRequest.method.trim() || !apiRequest.endpoint.trim() || !apiRequest.headers.trim() || attemptsLeft === 0}
              className="flex items-center gap-2"
              size="sm"
            >
              <CheckCircle className="w-4 h-4" />
              Check Request
            </Button>
            <Button
              variant="outline"
              onClick={handleShowHint}
              disabled={!isFormValid() || attemptsLeft === 0}
              className="flex items-center gap-2"
              size="sm"
            >
              <Lightbulb className="w-4 h-4" />
              Hint
            </Button>
          </div>
        </div>
      </Card>

      {/* Hint Section */}
      {showHint && isFormValid() && (
        <Card className="bg-gradient-to-r from-yellow-500/10 to-amber-500/10 border-yellow-500/30">
          <div className="flex items-start gap-4">
            <Lightbulb className="w-6 h-6 text-yellow-400 flex-shrink-0 mt-1" />
            <div>
              <h3 className="text-lg font-bold text-yellow-400 mb-2">💡 Hint #{hintsUsed}</h3>
              <p className="text-slate-300">{generateHint()}</p>
            </div>
          </div>
        </Card>
      )}

      {/* Result Section */}
      {result && (
        <Card className={`${
          result.correct 
            ? 'bg-gradient-to-r from-green-500/10 to-emerald-500/10 border-green-500/30' 
            : result.showAnswer
            ? 'bg-gradient-to-r from-red-500/10 to-orange-500/10 border-red-500/30'
            : 'bg-gradient-to-r from-yellow-500/10 to-orange-500/10 border-yellow-500/30'
        }`}>
          <div className="flex items-start gap-4">
            {result.correct ? (
              <CheckCircle className="w-8 h-8 text-green-400 flex-shrink-0" />
            ) : (
              <XCircle className="w-8 h-8 text-red-400 flex-shrink-0" />
            )}
            <div className="flex-1">
              <h3 className={`text-xl font-bold mb-2 ${
                result.correct ? 'text-green-400' : 'text-red-400'
              }`}>
                {result.correct ? '✓ Correct!' : '✗ Incorrect'}
              </h3>
              <p className="text-slate-300 mb-4">{result.message}</p>

              {/* Show errors if not correct and not showing answer */}
              {!result.correct && !result.showAnswer && result.errors && (
                <div className="bg-slate-900 rounded-lg p-3 border border-red-700 mb-4">
                  <p className="text-red-400 font-semibold mb-2">Issues found:</p>
                  <ul className="space-y-1">
                    {result.errors.map((error, idx) => (
                      <li key={idx} className="text-slate-300 text-sm flex items-start gap-2">
                        <span className="text-red-400">•</span>
                        <span>{error}</span>
                      </li>
                    ))}
                  </ul>
                </div>
              )}

              {/* Show answer if showAnswer is true */}
              {result.showAnswer && (
                <div className="space-y-3">
                  <div>
                    <p className="text-sm text-slate-400 mb-1">Correct HTTP Method:</p>
                    <div className="bg-slate-900 rounded-lg p-3 border border-green-700">
                      <code className="text-green-400 font-mono text-sm">{result.expectedMethod}</code>
                    </div>
                  </div>
                  <div>
                    <p className="text-sm text-slate-400 mb-1">Correct Endpoint:</p>
                    <div className="bg-slate-900 rounded-lg p-3 border border-green-700">
                      <code className="text-green-400 font-mono text-sm">{result.expectedEndpoint}</code>
                    </div>
                  </div>
                  <div>
                    <p className="text-sm text-slate-400 mb-1">Correct Headers:</p>
                    <div className="bg-slate-900 rounded-lg p-3 border border-green-700">
                      <code className="text-cyan-400 font-mono text-sm whitespace-pre">
                        {JSON.stringify(result.expectedHeaders, null, 2)}
                      </code>
                    </div>
                  </div>
                  {result.expectedBody && (
                    <div>
                      <p className="text-sm text-slate-400 mb-1">Correct Body:</p>
                      <div className="bg-slate-900 rounded-lg p-3 border border-green-700">
                        <code className="text-purple-400 font-mono text-sm whitespace-pre">
                          {JSON.stringify(result.expectedBody, null, 2)}
                        </code>
                      </div>
                    </div>
                  )}
                </div>
              )}
            </div>
          </div>

          {/* Try Again Button */}
          {(result.correct || result.showAnswer) && (
            <div className="mt-6 pt-6 border-t border-slate-700">
              <Button
                onClick={handleTryAnother}
                variant="outline"
                className="flex items-center gap-2"
              >
                <RotateCcw className="w-4 h-4" />
                Try Another Request
              </Button>
            </div>
          )}
        </Card>
      )}
    </div>
  );
};

export default APIRequestPractice;